## 【問題1】行列積を手計算する
参考URL  
https://jsciencer.com/higschmath/matrix/665/  
https://oversleptabit.com/archives/5173

行列積の1行1列目の値を計算
Aの1行目「-1, 2, 3」、Bの1列目「0, 0, 2」をかけて足す
-1×0＋2×0＋3×2＝6

行列積の1行2列目の計算
Aの1行目「-1, 2, 3」、Bの1列目「2, 2, 9」をかけて足す
-1×2＋2×2＋3×9＝29

行列積の1行3列目の計算
Aの1行目「-1, 2, 3」、Bの1列目「1, -8, -1」をかけて足す
-1×1＋2×(-8)＋3×(-1)＝-20

行列積の2行1列目の値を計算
Aの1行目「4, -5, 6」、Bの1列目「0, 0, 2」をかけて足す
4×0＋(-5)×0＋6×2＝12

行列積の2行2列目の計算
Aの1行目「4, -5, 6」、Bの1列目「2, 2, 9」をかけて足す
4×2＋(-5)×2＋6×9＝52

行列積の2行3列目の計算
Aの1行目「4, -5, 6」、Bの1列目「1, -8, -1」をかけて足す
4×1＋(-5)×(-8)＋6×(-1)＝38

行列積の3行1列目の値を計算
Aの1行目「7, 8, -9」、Bの1列目「0, 0, 2」をかけて足す
7×0＋8×0＋(-9)×2＝-18

行列積の3行2列目の計算
Aの1行目「7, 8, -9」、Bの1列目「2, 2, 9」をかけて足す
7×2＋8×2＋(-9)×9＝-51

行列積の3行3列目の計算
Aの1行目「7, 8, -9」、Bの1列目「1, -8, -1」をかけて足す
7×1＋8×(-8)＋(-9)×(-1)＝-48

\begin{pmatrix}
6 & 29 & -20\\
12 & 52 & 38 \\
-18 & -51 & -48
\end{pmatrix}

## 【問題2】NumPyの関数による計算
参考URL  
https://note.nkmk.me/python-numpy-matrix/

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(np.matmul(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [2]:
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## 【問題3】ある要素の計算を実装

In [3]:
a0k = a_ndarray[0:1,:] #1行3列
bk0 = b_ndarray[:, 0:1].reshape(1, 3) #3行1列を1行3列に
kakeru = a0k * bk0
tasu = np.sum(kakeru)
print(tasu)

6


## 【問題4】行列積を行う関数の作成
参考URL  
https://snowtree-injune.com/2019/11/23/matrix-product/

In [4]:
def gyouretsuseki (a = a_ndarray, b = b_ndarray):
    x = np.zeros(a_ndarray.shape)
    ii = 3
    kk = 3
    jj = 3
    for i in range(ii):
        for j in range(jj):
            for k in range(kk):
                x[i][j] = x[i][j] + a[i][k] * b[k][j]
    return x
print(gyouretsuseki())

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


## 【問題5】計算が定義されない入力を判定する
参考URL  
https://note.nkmk.me/python-numpy-ndarray-ndim-shape-size/

In [5]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

print(gyouretsuseki(d_ndarray, e_ndarray)

SyntaxError: unexpected EOF while parsing (<ipython-input-5-e7080e74e36d>, line 4)

In [6]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def gyouretsuseki2 (a = a_ndarray, b = b_ndarray):
    if a.shape[1] == b.shape[0]:
        x = np.zeros(a_ndarray.shape)
        ii = a.shape[0]
        kk = a.shape[1]
        jj = b.shape[1]
        for i in range(ii):
            for j in range(jj):
                for k in range(kk):
                    x[i][j] = x[i][j] + a[i][k] * b[k][j]
        return x
    else:
        return "列数と行数が異なるため計算できません"
    
print(gyouretsuseki2())
print(gyouretsuseki2(d_ndarray, e_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
列数と行数が異なるため計算できません


## 【問題6】転置
参考URL  
https://risalc.info/src/transpose-matrix-properties.html

In [7]:
ten_a = np.transpose(a_ndarray)
ten_b = np.transpose(b_ndarray)
toi6 = np.transpose(ten_b @ ten_a)
print(toi6)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [8]:
ten_a = (a_ndarray).T
ten_b = (b_ndarray).T
toi6 = (ten_b @ ten_a).T
print(toi6)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
